function visConfusion(ConfusionMatrix, RowLabels, ColLabels)
% visConfusion(ConfusionMatrix, RowLabels, ColLabels)
% Plot a confusion matrix with optional labels.
%
% For labeling purposes, it is assumed that each row represents the attempts
% to classify tokens generated by class X into one of the known classification
% categories Y.  Thus, ConfusionMatrix(i,j) is shows how many (or what 
% proportion) of class i was labeled as class j.
%
% RowLabels and ColLabels are optional.  Failure to provide either generates
% an index.  If RowLabels only is provided and the ConfusionMatrix is
% square, then the same labels will be used for the columns.
% The labels may either be numeric vectors or cell arrays of labels, e.g.
% {'wolf', 'sheep', 'shepherd'}

narginchk(1,3);  % Verify # input args

[Rows, Cols] = size(ConfusionMatrix);

switch nargin
    case 1, RowLabels=1:Rows; ColLabels=1:Cols;
    case 2
        if Rows == Cols
            ColLabels=RowLabels;
        else
            ColLabels=1:Cols;
        end
end

imagesc(ConfusionMatrix)  % Show matrix with color representing count
% Set tick marks for each class
set(gca, 'XTick', 1:Cols);
set(gca, 'YTick', 1:Rows);
% Set the labeles for each class
set(gca, 'XTickLabel', ColLabels);
set(gca, 'YTickLabel', RowLabels);
% Axis labels
xlabel('Classification')
ylabel('Generated by class')

colorbar;  % Show color to count scale

